---
- name: Include OS-specific variables
  include_vars: "{{ playbook_dir }}/group_vars/{{ ansible_os_family | lower }}.yml"

- name: Install RabbitMQ on Debian
  include_tasks: install_debian.yml
  when: ansible_distribution == 'Debian'

- name: Configure hosts on Debian
  include_tasks: configure_hosts.yml
  when: ansible_distribution == 'Debian'

- name: Configure RabbitMQ Plugins
  include_tasks: configure_plugins.yml

- name: Configure Cluster
  include_tasks: configure_cluster.yml

- name: Configure RabbitMQ Users and VHosts
  include_tasks: configure_users.yml
