---
rabbitmq_apt_key_url: "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key"
erlang_apt_repo: "deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/debian bullseye main"
erlang_apt_key_url: "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key"

rabittmq_main_key: "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA"
erlang_repository: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
rabbitmq_repository: "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key"

applications: 
  - curl
  - gnupg
  - apt-transport-https
  - vim

erlang_packages:
  - erlang
  - rabbitmq-server
  - erlang-base
  - erlang-asn1
  - erlang-crypto
  - erlang-eldap
  - erlang-ftp
  - erlang-inets
  - erlang-mnesia
  - erlang-os-mon
  - erlang-parsetools
  - erlang-public-key
  - erlang-runtime-tools
  - erlang-snmp
  - erlang-ssl
  - erlang-syntax-tools
  - erlang-tftp
  - erlang-tools
  - erlang-xmerl